# This file sources other files in `hyprland` and `custom` folders
# You wanna add your stuff in files in `custom`

$qsConfig = ii
#exec = hyprctl dispatch submap global # DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND
#submap = global # This is required for catchall to work

# Environment variables
source=hyprland/env.conf
source=custom/env.conf

# Defaults 默认配置
source=hyprland/execs.conf
source=hyprland/general.conf
source=hyprland/rules.conf
source=hyprland/colors.conf

exec = hyprctl dispatch submap global # DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND
submap = global # This is required for catchall to work
source=hyprland/keybinds.conf
bind = , escape, submap, reset # 退出 global submap 使自定义的快捷键正常工作
submap = reset

# Custom  私人配置项覆盖默认配置
source=custom/execs.conf
source=custom/general.conf
source=custom/animations.conf
source=custom/rules.conf
source=custom/keybinds.conf

# nwg-displays support
source=workspaces.conf
source=monitors.conf
