# Exec-once
# ~/.config/hypr/hyprland/exec-once.conf
# Something stuff exec once on login
# ===================================================================

# Notification daemon (通知 [ 和 ags 的 inotify-tools 冲突暂时屏蔽 ]
# exec-once = dunst
# ===================================================================

# Bar
exec-once = $BAR

# Wallpaper init
exec-once = $WALLPAPER_DAEMON

# 自动切换壁纸脚本
 exec-once = $AOTU_SWITCH_WALLPAPER
# ===================================================================

# 自动旋转屏幕 (需要硬件支持) 
# # exec-once = iio-hyprland DSI-1  ## auto rotate DSI-1 monitor
# ===================================================================

# Fcitx5 输入法
exec-once = $IME
# ===================================================================

# Wlsunset gama (屏幕伽马值，需要wlsunset程序)
# exec-once = wlsunset -l 39.9 -L 116.3
# ===================================================================

# Cliphist history store (剪切板配置
exec-once = wl-paste --type text --watch cliphist store   # 存储文本
exec-once = wl-paste --type image --watch cliphist store  # 存储图片
exec-once = wl-clip-persist --clipboard both              # Use Regular and Primary clipboard,long :w
# ===================================================================

# polkit-kde-authentication-agent-1
# exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = systemctl --user start hyprpolkitagent
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# ===================================================================

# ORC POT (Break: 待修复)
# exec-once = pot
# ===================================================================

# Cursor-theme
exec = hyprctl setcursor Bibata-Modern-Ice 20
exec = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec = gsettings set org.gnome.desktop.interface cursor-size 20
# ===================================================================

# Xrdb xwayland dpi fix
exec-once = xrdb ~/.Xresource
