# 2025-07-06
# 此配置存放所有的group 相关配置
# Variables:general,binds,group
# Keybinds
# window_rules

# ## Colors: #c23c7f Default
# ====| #ef5b9c:踯躅 | #ea66a6:牡丹 | #c77eb5:菖蒲 | #f05b72:蔷薇 | #f173ac:赤紫 |====

# ====| #f15b6c:韩红 | #ca8687:薄柿 | #5f3c32:枯茶 | #6b473c:焦茶 | #6d5826:鹭茶 |====

# ====| #444693:绀桔 | #2b4490:花   | #2a5caa:瑠璃 | #102b6a:青蓝 | #4e72b8:群青 |====

# ____________________________________________________________________________________________________________
general {
    # Group 组边框颜色
    col.nogroup_border        = rgb(ffaaff) # 对于禁止加入组的 非活动 窗口的边框颜色（请参阅 wiki denywindowfromgroup 调度程序）
    col.nogroup_border_active = rgb(ff00ff) # 对于禁止加入组的 活动   窗口的边框颜色

  }

binds {
    ignore_group_lock        = false  # 启用后，dispatchers moveintogroup moveoutofgroup movewindoworgroup 将会忽略组锁定
    movefocus_cycles_groupfirst = false # 启用，在分组窗口中时 移动焦点将循环组中窗口，然后在选项卡的每一端移动到其他窗口/组
  }

group { #[v0.30.0]
    auto_group = true                    # 新建窗口自动分组到聚焦的解锁组中 如果只想对特定窗口禁用 auto_group 设置 goup barred窗口规则

    # 窗口入组
    insert_after_current    = true       # 组中新窗口在当前窗口之后，or 组尾生成 [需要测试默认行为 组尾生成？]
    drag_into_group         = 2          # 将窗口拖动到未锁定的组中是否会将它们合并，0：禁用，1：启用，2：仅当拖入组栏时
    merge_groups_on_drag    = true       # 窗口组是否可以拖入其他组合并
    merge_groups_on_groupbar = true      # 当将一个组拖入另一个组栏时与另一个组合并
    merge_floated_into_tiled_on_groupbar = false # 将浮动窗口拖动到平铺窗口组栏是否会将它们合并
    group_on_movetoworkspace = false     # 使用 movetoworkspace[silent] 是否会将窗口合并到工作区的单独解锁组中 [当有多个为解锁组是否不会合并？]

    # 窗口出组
    focus_removed_window    = false      # 是否聚焦于刚移除群组的窗口

    col.border_active           = rgb(8D54E0) # 活动组边框颜色   -聚焦
    col.border_inactive         = rgb(40E0D0) # 非活动组边框颜色 -失焦 {#40E0D0:只此青绿,}
    col.border_locked_active    = rgb(E60000) # locked组边框颜色 -聚焦
    col.border_locked_inactive  = rgb(900021) # locked组边框颜色 -失焦

    groupbar { # group:groupbar
      enabled              = true         # 启用groupbar

      # 字体
      font_family          = [[Empty]]    # 用于显示组标题栏的字体，未指定使用 misc:font_family
      font_size            = 12           # 标题字体大小(8)
      font_weight_active   = normal       # 活动组标题的字体粗细 (font_weight:normal or num )
      font_weight_inactive = normal       # 非活动组标题的字体粗细 

      scrolling            = true         # 在组拦中滚动是否更改活动窗口
      height               = 14           # 组栏的高度
      indicator_gap        = 0            # 组栏指示器和标题之间的间隙高度
      stacked              = false        # 将组栏渲染为垂直堆栈
      priority             = 3            # 设置组栏的装饰优先级别 [优先级？ 渲染优先级？显示优先级？]
      render_titles        = false        # 窗口组标题显示 (true)
      text_offset          = 0            # 标题文字的垂直位置
      rounding             = 1            # 组指示器圆角
      gradients            = false        # 组窗口标题栏是否绘制渐变梯度 [?]
      gradient_rounding    = 2            # gradient 圆角
      round_only_edges     = true         # 圆角仅在groupbar
      gradient_round_only_edges = true    # 


      text_color           = 0xffffffff   # (0xffffffff) 组标题栏文字颜色
      text_color_inactive  = unset        # 非活动组标题文字颜色 (default:text_color)
      text_color_locked_active = unset    # 锁定组中的非活动组标题颜色 (default:text_color_inactive)
      col.active           = 0x66777700   # 活动组栏背景颜色
      col.inactive         = 0x66ff5500   # 非活动组栏背景颜色
      col.locked_active    = 0x66ff5500   # 活动锁定组边框颜色
      col.locked_inactive  = 0x66775500   # 非活动锁定组边框颜色
      gaps_in              = 2            # 渐变之间的间隙大小
      gaps_out             = 2            # 渐变和窗口之间的间隙大小
      keep_upper_gap       = true         # 是否添加 upper gap
      }
  }
