# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#131318

# Main text color
theme[main_fg]=#E4E1E9

# Title color for boxes
theme[title]=#E4E1E9

# Highlight color for keyboard shortcuts
theme[hi_fg]=#C1C1FF

# Background color of selected item in processes box
theme[selected_bg]=#1F1F25

# Foreground color of selected item in processes box
theme[selected_fg]=#C1C1FF

# Color of inactive/disabled text
theme[inactive_fg]=#918F9A

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#E9B9D3

# Background color of the percentage meters
theme[meter_bg]=#918F9A

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#E9B9D3

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#cba6f7
theme[mem_box]=#a6e3a1
theme[net_box]=#eba0ac
theme[proc_box]=#89b4fa

# Box divider line and small boxes line color
theme[div_line]=#47464F

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#a6e3a1
theme[temp_mid]=#f9e2af
theme[temp_end]=#f38ba8

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#94e2d5
theme[cpu_mid]=#74c7ec
theme[cpu_end]=#b4befe

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#cba6f7
theme[free_mid]=#b4befe
theme[free_end]=#89b4fa

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#74c7ec
theme[cached_mid]=#89b4fa
theme[cached_end]=#b4befe

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#fab387
theme[available_mid]=#eba0ac
theme[available_end]=#f38ba8

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#a6e3a1
theme[used_mid]=#94e2d5
theme[used_end]=#89dceb

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#fab387
theme[download_mid]=#eba0ac
theme[download_end]=#f38ba8

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#a6e3a1
theme[upload_mid]=#94e2d5
theme[upload_end]=#89dceb

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#74c7ec
theme[process_mid]=#b4befe
theme[process_end]=#cba6f7
