[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\xe/home/awarewen)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\a\x80\0\0\0\0\0\0\v\x18\0\0\x1\xdd\0\0\0\0\0\0\0\0\0\0\x3\x98\0\0\x1\xdd\0\0\0\x1\x2\0\0\0\a\x80\0\0\a\x80\0\0\0\0\0\0\v\x18\0\0\x1\xdd)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(600 0)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Mediainfo]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\a\x80\0\0\0\0\0\0\t8\0\0\x2^\0\0\0\0\0\0\0\0\0\0\x1\xdf\0\0\x2^\0\0\0\x1\x2\0\0\0\a\x80\0\0\a\x80\0\0\0\0\0\0\t8\0\0\x2^)

[OpenDialog]
advanced=false
size=@Size(557 443)

[RecentsMRL]
list=file:///home/awarewen/Videos/av/new5/hhd800.com%40CLUB-677.mp4, file:///home/awarewen/./a.mp4
times=0, 0
