[metadata]
version = 2.4.0
timestamp = 2025-07-07 00:17:24.101944+08:00

[vdu-controls-globals]
splash-screen-enabled = yes
system-tray-enabled = no
hide-on-focus-out = no
smart-window = yes
smart-uses-xcb = yes
monochrome-tray-enabled = no
mono-light-tray-enabled = no
protect-nvram = yes
order-by-name = no
lux-options-enabled = yes
lux-tray-icon = yes
schedule-enabled = yes
weather-enabled = yes
dbus-client-enabled = yes
dbus-events-enabled = no
syslog-enabled = no
debug-enabled = no
warnings-enabled = no
translations-enabled = no
location = 
ddcutil-emulator = 

[vdu-controls-widgets]
brightness = yes
contrast = yes
audio-volume = no
audio-mute = no
audio-treble = no
audio-bass = no
audio-mic-volume = no
input-source = no
power-mode = no
osd-language = no
color-preset = no
color-temperature = yes
enable-vcp-codes = 

[ddcutil-parameters]
sleep-multiplier = 0.0
ddcutil-extra-args = 

[ddcutil-capabilities]
capabilities-override = 

