# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing
$APP_LAUNCHER = $HOME/.config/rofi/scripts/launcher_t2  # ## rofi launcher and theme(themes: https://github.com/adi1090x/rofi)
bind = super,  space,  execr,   $APP_LAUNCHER

