# hypridle 触发细节
# 使用 keybind 调用 loginctl lock-session 发送一个锁定事件
# 当 hypridle daemon 监听到 锁定事件发生 则执行 lock_cmd
$lock_cmd = hyprctl dispatch global quickshell:lock # pidof hyprlock || hyprlock
general {
    lock_cmd = $lock_cmd               # 收到锁屏事件运行
    #unlock_cmd = notify-send "unlock!"                  # 收到解锁事件运行
    on_lock_cmd = sleep 3 && hyprctl dispatch dpms off  # 当会话锁定时运行
    before_sleep_cmd = loginctl lock-session    # 收到 dbus prepare_sleep 事件运行 command ran before sleep
    after_sleep_cmd = hyprctl dispatch global quickshell:lockFocus  # 收到 dbus post prepare_sleep 事件运行 command ran after sleep
    ignore_dbus_inhibit = false             # 是否忽略 dbus 发送的空闲抑制事件 whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    ignore_systemd_inhibit = false          # 是否忽略 systemd- inhibit -what=idle 抑制 whether to ignore systemd-inhibit --what=idle inhibitors
    ignore_wayland_inhibit = false          # 是否忽略 wayland 协议空闲抑制
    inhibit_sleep = 2                       # 睡眠抑制，0:禁用，1:正常，2:自动, 3:锁定通知
}

listener { # 监听空闲
    timeout = 500                              # in seconds
    on-timeout = hyprctl dispatch dpms off     # command to run when timeout has passed
    on-resume =  hyprctl dispatch dpms on      # command to run when activity is detected after timeout has fired.
    ignore_inhibit = false                     # 忽略此规则的空闲抑制(所有类型)
}
