 # This file is to be overwritten by nwg-displays if you choose to use it.
# nwg-displays is a graphical tool for managing monitors. 
# - Installation for Arch Linux: sudo pacman -S nwg-displays
# - Repo: https://github.com/nwg-piotr/nwg-displays
#
#
# ===================================================================
#                            Monitors (双屏)
# # 1.Add a (, cm, X) to change default sRGB output preset
# auto: 自动，对于8bpc使用sRGB，如果支持则使用wide
# srgb: sRGB原色(default)
# wide: 广色域 BT2020原色
# edid: edid 原色
# hdr: 广色域和 HDR PQ
# hdredid: hdr 使用 edid 原色
#
# # 2.手动设置 mode模式
# monitor = DP-1, modeline 1071.101 3840 3848 3880 3920 2160 2263 2271 2277 +hsync -vsync, 0x0, 1
#
# # 3.resolutions opt
# preferred：首选尺寸和刷新率
# highres：支持的最高分辨率
# maxwidth：支持的最宽分辨率
#
# # 4.position opt
# auto：默认会把新显示器放于右侧，使用显示器左上角作为原点
# auto-right/left/up/down
# auto-center-right/left/up/down
#
# # 5.镜像显示 mirror (,mirror, <MONIROR-NAME>)
# # 6.sdrbrightness, B 和 sdrsaturation, S 控制 HDR 模式下的 SDR 亮度和饱和度，默认为 1.0 (Typical: 1.0 - 2.0)
# # 7.vrr 可变刷新率 （,vrr, x) x来自 misc:vrr
# ===================================================================
monitorv2 { # monitor 拓展屏
# monitor = HDMI-A-1, 3840x2160@59.997002, 1920x0, 2, transform, 0 #,  bitdepth, 10 # bitdepth, 10
    output = HDMI-A-1
    mode = 3840x2160@59.997002
    position = 1920x0
    scale = 2
    transform = 0
    cm = hdr
    bitdepth = 10
    sdrbrightness = 1.0
    sdrsaturation = 1.0
  }

monitorv2 { # 笔记本内屏
# monitor = DSI-1,    1200x1920@60.000000, 0x0,    1, transform, 3, , cm, hddr, bitdepth, 10
    output = DSI-1
    mode = 1200x1920@60.000000
    position = 0x0
    scale = 1.2
    transform = 3
    cm = hdr
    bitdepth = 10
    sdrbrightness = 1.0
    sdrsaturation = 1.0
  }

monitor =      ,    preferred,           auto,   1                                # 用于快速识别其他便携显示器
monitor = DSI-1,    addreserved,         0,10,10,10                               # 添加屏幕保留区域(不被平铺窗口占用)
