# This file is to be overwritten by nwg-displays if you choose to use it.
# nwg-displays is a graphical tool for managing monitors. 
# - Installation for Arch Linux: sudo pacman -S nwg-displays
# - Repo: https://github.com/nwg-piotr/nwg-displays
# ===================================================================
#                            工作区绑定
# 将工作区绑定到确定的屏幕可以避免一些与工作区相关的未知问题
# ===================================================================
workspace = 1,  monitor:DSI-1,    default:true
workspace = 2,  monitor:DSI-1,    default:true
workspace = 3,  monitor:HDMI-A-1, default:true
workspace = 4,  monitor:HDMI-A-1, default:true
