[General]
MachineLine=E1859641
SerialCode=JBiZ01/dOCzP3hE11lE96qHa9OTKkOsDhEajpCrKssWkJv9vckw5NC/KL2K0mLZZ
SerialCode1=JBiZ01/dOCzP3hE11lE96qHa9OTKkOsDhEajpCrKssWkJv9vckw5NC/KL2K0mLZZ
TimesLeft3=820711
regDate=Fri Jul 26 2024
