#!/usr/bin/env bash
# 脚本用法及参数: screenshot (1|2|3) {1-9} {1-9}
# 第一个参数为截图方案：
# 1 ) # 选区截图后发送剪切板
# 2 ) # 当前显示器全屏截图后直接发送剪切板
# 3 ) # 活动窗口截图后直接发送剪切板

## Add to hyprland windowrule config
# ===========================

# 质量初始化
QUALITY=$2

# 窗口截屏时留的边距
pos_lu=20 # lu: left up
pos_rd=40 # rd: right down

function focused_window {
  grim -l $QUALITY -g "$(hyprctl activewindow -j |
    gojq -j '.at[0]-($gaps_lu | tonumber), ",", .at[1]-($gaps_lu | tonumber), " ", .size[0]+($gaps_rd | tonumber), "x", .size[1]+($gaps_rd | tonumber)' --arg gaps_lu $pos_lu --arg gaps_rd $pos_rd)" - |
    satty -c "$XDG_CONFIG_DIR/satty/config.toml" -f - --copy-command wl-copy --early-exit
}

function take_fullscreen {
  if $EDIT; then
    grim -l $QUALITY -g "$(slurp -b "#ef5b9c30" -d)" - |
      satty -f - --copy-command wl-copy --early-exit
  else
    grim -l $QUALITY -o "$(hyprctl monitors -j | gojq '.[] | select(.focused == true) | .name' -r)" - |
      wl-copy
  fi
}

function take_select_edit {
  grim -l $QUALITY -g "$(slurp -b "#ef5b9c30" -d)" - |
    satty -f - --copy-command wl-copy --early-exit
}

function take_select {
  grim -l $QUALITY -g "$(slurp -b "#ef5b9c30" -d)" - |
    wl-copy
}

case $1 in
1) # 选区截图后发送剪切板
  take_select
  ;;

2) # 当前显示器全屏截图后直接发送剪切板
  EDIT=false

  take_fullscreen
  ;;

3) # 活动窗口截图后直接发送剪切板
  focused_window
  ;;

4) # 当前显示器全屏截图后编辑
  #EDIT=true
  #pause_focused_screen &
  #take_fullscreen
  grim -l 1 -o $(hyprctl monitors -j | gojq '.[] | select(.focused == true) | .name' -r) - |
    satty -f - --fullscreen --init-tool crop --copy-command wl-copy --early-exit
  ;;
esac
